-- Создание базы данных
-- CREATE DATABASE patient_registry;

-- Подключение к базе данных
-- \c patient_registry;

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица пациентов
CREATE TABLE IF NOT EXISTS patients (
    id SERIAL PRIMARY KEY,
    surname VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    patronymic VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    email VARCHAR(255) NOT NULL,
    index VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    polisIndex VARCHAR(255) NOT NULL,
    polisCompany VARCHAR(255) NOT NULL,
    polisDate DATE NOT NULL,
    socialStatus INTEGER,
    socialStatusText TEXT,
    specialMarks TEXT,
    physicalDevelopmentWorkshop integer,
    assessmentDynamicsSexualDevelopment text,
    presenceGynecologicalDiseasesAnamnesis text,
    presenceChronicExtragenitalDiseases text,
    groupHealth integer,
    finalGynecologicalDiagnosis text,
    factorsRisk text,
    preventionRecommendations text,
    idListDiseases integer,
    idListDiseasesGynecologica integer,
    idParents integer,
    idFeaturesIntrauterineDevelopmentChild integer,
    idFeatureNewbornPeriod integer,
    idAssessmentGirlPhysicalDevelopmentAge1type1 integer,
    idAssessmentGirlPhysicalDevelopmentAge1type2 integer,
    idAssessmentGirlPhysicalDevelopmentAge1type3 integer,
    idAssessmentGirlPhysicalDevelopmentAge1type4 integer,
    idAssessmentGirlPhysicalDevelopmentAge1type5 integer,
    idAssessmentGirlPhysicalDevelopmentAge1type6 integer,
    idAssessmentGirlPhysicalDevelopmentAge1type7 integer,
    idAssessmentGirlPhysicalDevelopmentAge2type8 integer,
    idAssessmentGirlPhysicalDevelopmentAge2type9 integer, 
    idAssessmentGirlPhysicalDevelopmentAge2type10 integer,
    idAssessmentGirlPhysicalDevelopmentAge2type11 integer, 
    idAssessmentGirlPhysicalDevelopmentAge3type12 integer,
    idAssessmentGirlPhysicalDevelopmentAge3type13 integer,
    idAssessmentGirlPhysicalDevelopmentAge3type14 integer,
    idAssessmentGirlPhysicalDevelopmentAge3type15 integer,
    idAssessmentGirlPhysicalDevelopmentAge3type16 integer,
    idAssessmentGirlPhysicalDevelopmentAge3type17 integer,
    idAssessmentGirlPhysicalDevelopmentAge3type18 integer,
    created_by INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS listDiseases (
    id SERIAL PRIMARY KEY,
    listDiseases0 TEXT,
    listDiseasesGroup0 TEXT,
    listDiseases1 TEXT,
    listDiseasesGroup1 TEXT,
    listDiseases2 TEXT,
    listDiseasesGroup2 TEXT,
    listDiseases3 TEXT,
    listDiseasesGroup3 TEXT,
    listDiseases4 TEXT,
    listDiseasesGroup4 TEXT,
    listDiseases5 TEXT,
    listDiseasesGroup5 TEXT,
    listDiseases6 TEXT,
    listDiseasesGroup6 TEXT,
    listDiseases7 TEXT,
    listDiseasesGroup7 TEXT,
    listDiseases8 TEXT,
    listDiseasesGroup8 TEXT,
    listDiseases9 TEXT,
    listDiseasesGroup9 TEXT,
    listDiseases10 TEXT,
    listDiseasesGroup10 TEXT,
    listDiseases11 TEXT,
    listDiseasesGroup11 TEXT,
    listDiseases12 TEXT,
    listDiseasesGroup12 TEXT,
    listDiseases13 TEXT,
    listDiseasesGroup13 TEXT,
    listDiseases14 TEXT,
    listDiseasesGroup14 TEXT,
    listDiseases15 TEXT,
    listDiseasesGroup15 TEXT,
    listDiseases16 TEXT,
    listDiseasesGroup16 TEXT,
    listDiseases17 TEXT,
    listDiseasesGroup17 TEXT,
    listDiseases18 TEXT,
    listDiseasesGroup18 TEXT
    );

CREATE TABLE IF NOT EXISTS listDiseasesGynecologica (
    id SERIAL PRIMARY KEY,
    listDiseasesGynecological0 TEXT,
    listDiseasesGynecological1 TEXT,
    listDiseasesGynecological2 TEXT,
    listDiseasesGynecological3 TEXT,
    listDiseasesGynecological4 TEXT,
    listDiseasesGynecological5 TEXT,
    listDiseasesGynecological6 TEXT,
    listDiseasesGynecological7 TEXT,
    listDiseasesGynecological8 TEXT,
    listDiseasesGynecological9 TEXT,
    listDiseasesGynecological10 TEXT,
    listDiseasesGynecological11 TEXT,
    listDiseasesGynecological12 TEXT,
    listDiseasesGynecological13 TEXT,
    listDiseasesGynecological14 TEXT,
    listDiseasesGynecological15 TEXT,
    listDiseasesGynecological16 TEXT,
    listDiseasesGynecological17 TEXT,
    listDiseasesGynecological18 TEXT
);

CREATE TABLE IF NOT EXISTS parents (
    id SERIAL PRIMARY KEY,
    fatherHeight TEXT,
    fatherWeight TEXT,
    fatherPhysique integer,
    fatherProfDamageChildText text,
    fatherBadHabitsVariant text,
    fatherSpetialDiseasText text,
    fatherRelativeSpetialDiseasText text,
    fatherIndirectSignsEndocrineImbalance text,
    fatherIPPP text,
    fatherPathologyGenitalOrgans text,
    fatherOperationSexualOrgan text,
    fatherInfertility text,
    fatherMethodConceptionChild text,
    fatherAgeTimeBirthChild integer,
    fatherSpetialNotes text,
    motherHeight TEXT,
    motherWeight TEXT,
    motherPhysique integer,
    motherProfDamageChildText text,
    motherBadHabitsVariant text,
    motherSpetialDiseasText text,
    motherRelativeSpetialDiseasText text,
    motherIndirectSignsEndocrineImbalance text,
    motherMenstrualCycle text,
    motherPreviousGynecologicalDiseases text,
    motherIPPP text,
    motherPreviousChemotherapyTherapy text,
    motherGynecologicalOperation text,
    motherInfertility text,
    motherContraceptionEvePregnancy text,
    motherPregnancy text,
    motherMethodConceptionChild text,
    motherAttemptTerminatePregnancy text,
    motherAgeTimeBirthChild integer
);


CREATE TABLE IF NOT EXISTS featuresIntrauterineDevelopmentChild (
    id SERIAL PRIMARY KEY,
    toxicosisFirstHalfPregnancy text,
    toxicosisSecondHalfPregnancy text,
    signsThreatenedTerminationPregnancy text,
    acuteDiseasesSurgicalInterventionsMother text,
    useHormonalDrugsMother text,
    signsFetalSuffering text,
    bornWeekPregnancy integer,
    childbirth text,
    specialMarksDevelopment text,
);

CREATE TABLE IF NOT EXISTS featureNewbornPeriod (
    id SERIAL PRIMARY KEY,
    newbornHeight TEXT,
    newbornWeight TEXT,
    estimateApgar text,
    newbornCondition text,
    trauma text,
    newbornDysembriogenesis text,
    abnormalitiesStructureConditionMammaryGlands text,
    abnormalitiesStructureExternalGenitalia text,
    newbornPostponedOperations text,
    newbornBCG text,
    newbornDischargedFromMaternityHospital integer,
    newbornSheDepartmentPhysiology text,
    newbornTransferredChildrenHospital integer,
    newbornSheTookHormonalMedications text,
    newbornDegreeRiskReproductiveDisorders INTEGER,
    newbornSpecialMarksRecommendations text
    );


CREATE TABLE IF NOT EXISTS assessmentGirlPhysicalDevelopmentAge1type ( --возраст 1-7
    id SERIAL PRIMARY KEY,
    assessmentHeight TEXT,
    assessmentWeight TEXT,
    assessmentBreastEnlargement text,
    assessmentPresencePathologicalFormations text,
    assessmentAbnormalitiesStructureExternalGenitalia text,
    assessmentRostvolos text,
    assessmentPathologicalDischarge text,
    assessmentHyperemiaSkin text,
    assessmentRecommendationsGenitalHygiene integer,
    assessmentReusableDiapers integer,
    assessmentPediatricianReport integer,
    assessmentConclusionPediatricGynecologist text,
    assessmentDegreeRiskReproductiveDisorders integer,
    assessmentSpecialMarks text
    );

CREATE TABLE IF NOT EXISTS assessmentGirlPhysicalDevelopmentAge2type ( --возраст 8-11
    id SERIAL PRIMARY KEY,
    assessmentHeight TEXT,
    assessmentWeight TEXT,
    assessmentBadHabits TEXT,
    assessmentSexualCharacteristics TEXT,
    assessmentPathologicalFormations TEXT,
    assessmentRhythmFeatures TEXT,
    assessmentHairGrowth TEXT,
    assessmentPresenceAcne TEXT,
    assessmentStructureExternalGenitalia TEXT,
    assessmentAbnormalitiesStructure TEXT,
    assessmentPathologicalDischarge TEXT,
    assessmentGipermia TEXT,
    assessmentNocturnalEnuresis integer,
    assessmentDaytimeIncontinence integer,
    assessmentStressIncontinence integer,
    assessmentPresenceStains integer,
    assessmentComplaintsPain integer,
    assessmentPresenceSignsViolence integer,
    assessmentRecimendation integer,
    assessmentUterus TEXT,
    assessmentAppendages TEXT,
    assessmentConditionVagina TEXT,
    assessmentConditionCervix TEXT,
    assessmentGynecologistReport TEXT,
    assessmentDegreeRisk TEXT,
    assessmentPediatricianReport integer,
    assessmentConclusionPediatricGynecologist TEXT,
    assessmentDegreeRiskReproductiveDisorders integer,
    assessmentSpecialMarks text,
    );



CREATE TABLE IF NOT EXISTS assessmentGirlPhysicalDevelopmentAge3type ( --возраст 12-18
    id SERIAL PRIMARY KEY,
    assessmentHeight TEXT,
    assessmentWeight TEXT,
    assessmentBadHabits TEXT,
    assessmentSexualCharacteristics TEXT,
    assessmentPathologicalFormationss TEXT,
    assessmentRhythmFeatures TEXT,
    assessmentHairGrowth TEXT,
    assessmentPresenceStripes TEXT,
    assessmentPresenceAcne TEXT,
    assessmentStructureExternalGenitalia TEXT,
    assessmentAbnormalitiesStructure TEXT,
    assessmentPathologicalDischarge TEXT,
    assessmentHyperemiaSkin TEXT,
    assessmentNocturnalEnuresis integer,
    assessmentDaytimeIncontinence integer,
    assessmentStressIncontinence integer,
    assessmentPresenceStains integer,
    assessmentComplaintsPain integer,
    assessmentPresenceSignsViolence integer,
    assessmentRecimendation integer,
    assessmentUterus TEXT,
    assessmentAppendages TEXT,
    assessmentConditionVagina TEXT,
    assessmentConditionCervix TEXT,
    assessmentSex integer,
    assessmentNumberPartners integer,
    assessmentContraception TEXT,
    assessmentMotivation integer,
    assessmentPregnancy TEXT,
    assessmentComplications TEXT,
    assessmentGynecologistReport TEXT,
    assessmentDegreeRisk TEXT,
    assessmentSpecialMarks TEXT,
    assessmentPediatricianReport integer,
    assessmentConclusionPediatricGynecologist TEXT
    )


